/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:794f5f2f-308d-406d-b06d-a30cc5977592",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_hjRJUZ8bD",
    "aws_user_pools_web_client_id": "3n3ln42ipu1fsbupjhcgi4acre",
    "oauth": {}
};


export default awsmobile;
